name = "cloud-mail-dev"
main = "src/index.js"
compatibility_date = "2025-06-04"
compatibility_flags = ["nodejs_als"]
keep_vars = true

[observability]
enabled = true

[dev]
ip = "0.0.0.0"

[[d1_databases]]
binding = "db"
database_name = "email"
database_id = "your-dev-d1-database-id"

[[kv_namespaces]]
binding = "kv"
id = "your-dev-kv-namespace-id"

#[[r2_buckets]]
#binding = "r2"
#bucket_name = "email"

#[ai]
#binding = "ai"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*", "/attachments/*", "/static/*"]

[[send_email]]
name = "email"


[vars]
ai_model = ""
analysis_cache = false
orm_log = false
domain = ["example.com", "example2.com", "example3.com", "example4.com"]
admin = "admin@example.com"
jwt_secret = "your-jwt-secret"	#本地私填,不要提交真实密钥
cors_origins = ""
resend_webhook_secret = ""
